'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Articulo
    Public Property id_articulo As Integer
    Public Property nombre As String
    Public Property precio As Decimal
    Public Property id_tipo As Integer

    Public Overridable Property TipoArticulo As TipoArticulo

End Class
