'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoArticulo
    Public Property id_tipo As Integer
    Public Property tipo As String

    Public Overridable Property Articulos As ICollection(Of Articulo) = New HashSet(Of Articulo)

End Class
